### ISSUE TITLE
Micro stutters with textures applied

### ISSUE THREAD

**Issue by MarcoDjallo** [NR74W/WipEout-Pulse-HD-Texture-Pack#5]
Hello,

first of all, thanks for this great work that brings freshness into this fantastic game.

I noticed that the game stutters when textures are applied.
I tried different options (changing renderer, options about textures, enabling frameskip...) but nothing changed, and I'm pretty sure it's not a performance problem (I have an i7 7700hq, gtx 1050, 16 gb ram, nvme ssd), also because from what I've read on the web seems a common problem of PPSSPP when external textures are applied.

From PPSSPP github, I read about .zim files as textures and how they can reduce loading times and consequently stutters. You can find some infos [here](https://github.com/hrydgard/ppsspp/pull/14467) and also [here](https://github.com/hrydgard/ppsspp/issues/12332#issuecomment-846764577).

Do you also have stutters? There's the possibility you consider converting the texture pack to zim to improve loading times?

Thank you in any case!

**Comment by NR74W** [comment]
Hi, and thanks. Sorry for the late reply, for some reason I was not informed earlier about this issue.

Thanks for letting me know about this file format and for your feedback. After converting the texture pack to ZIM, although it doesn't completely eliminate the stuttering, the game runs much smoother now. The only drawback is that the pack is slightly bigger now (835MB>1009MB).

I have created a new branch named "zim-format" with the converted textures, and renamed the master branch "png-format". Can you test the ZIM texture pack? If it's good enough, I can close this issue. Thanks in advance.

**Comment by MarcoDjallo** [comment]
Thank you very much,

unfortunately, the .zim pack does not seems to load for me. I followed the istructions as I did for the .png pack, but while this one loads, the .zim doesn't.

Do I have to check some other options to enable loading of zim files?

I tried to search on the web but I can't find anything about that.

**Comment by NR74W** [comment]
No problem.

The support for ZIM in texture replacements has only been added since PPSSPP v1.11.3-694 (released on 2021-05-24).  
Using the latest development build works: https://www.ppsspp.org/downloads.html

**Comment by MarcoDjallo** [comment]
Got it thanks, now it works.

I have to say, I can "feel" the stutters but can't "see" them. It's definitevely better than before.

Thank you very much for the incredible work you did on this great game!
